name: "run-deterministic-zip"
description: "GitHub Action to integrate https://github.com/timo-reymann/deterministic-zip the easy way."
author: "Timo Reymann <github@timo-reymann.de>"

branding:
  icon: 'box'
  color: 'orange'

inputs:
  args:
    description: Arguments to pass to deterministic-zip
    required: false
    default: ""
  target:
    description: Target file to create, including extension
    required: true
  source:
    description: Sources to zip
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "-r ${{ inputs.target }} ${{ inputs.source }} ${{ inputs.args }}"

